### ISSUE TITLE
Some packages to fix

### ISSUE THREAD

**Issue by ghost** [tsaop/crux-kf5#4]
Hello! First, thank you so much for your work with ports. I trying to install "frameworks-meta plasma-meta applications-meta" but some packages fail to install or to download. 

The package list:

rlog: https://github.com/vgough/rlog
encfs: https://github.com/vgough/encfs
libcanberra: https://github.com/Distrotech/libcanberra
gtk-doc: https://github.com/GNOME/gtk-doc
libaccounts-glib: https://github.com/ubports/libaccounts-glib
libaccounts-qt: https://github.com/ubports/libaccounts-qt
kfilemetadata
signon-ui: https://github.com/mardy/signon-ui
ballo
kaccounts-integration
kaccounts-providers
baloo-widgets

I ignored all these packages during installation. Several of them depend on each other. Can you fix this?

Many thanks! :+1:

**Comment by tsaop** [comment]
Hello,

I tried to redownload all of the packages you mentioned and the download proceeds without issue.
Can you attach the error message you get during the download or installation?

Thank you.

**Comment by ghost** [comment]
rlog for example:


prt-get: installing /usr/ports/romster/rlog
=======> Downloading 'http://rlog.googlecode.com/files/rlog-1.4.tar.gz'.
=======> Partial download found, trying to resume
--2018-02-27 13:49:53--  http://rlog.googlecode.com/files/rlog-1.4.tar.gz
Resolving rlog.googlecode.com... 64.233.190.82, 2800:3f0:4003:c01::52
Connecting to rlog.googlecode.com|64.233.190.82|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-02-27 13:49:53 ERROR 404: Not Found.

=======> Partial download failed, restarting
--2018-02-27 13:49:53--  http://rlog.googlecode.com/files/rlog-1.4.tar.gz
Resolving rlog.googlecode.com... 64.233.190.82, 2800:3f0:4003:c01::52
Connecting to rlog.googlecode.com|64.233.190.82|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-02-27 13:49:53 ERROR 404: Not Found.

=======> ERROR: Downloading 'http://rlog.googlecode.com/files/rlog-1.4.tar.gz' failed.
prt-get: error while install

-- Packages where install failed
rlog


encfs

'prt-get: installing /usr/ports/romster/rlog
=======> Downloading 'http://rlog.googlecode.com/files/rlog-1.4.tar.gz'.
=======> Partial download found, trying to resume
--2018-02-27 13:50:51--  http://rlog.googlecode.com/files/rlog-1.4.tar.gz
Resolving rlog.googlecode.com... 64.233.190.82, 2800:3f0:4003:c01::52
Connecting to rlog.googlecode.com|64.233.190.82|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-02-27 13:50:51 ERROR 404: Not Found.

=======> Partial download failed, restarting
--2018-02-27 13:50:51--  http://rlog.googlecode.com/files/rlog-1.4.tar.gz
Resolving rlog.googlecode.com... 64.233.190.82, 2800:3f0:4003:c01::52
Connecting to rlog.googlecode.com|64.233.190.82|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-02-27 13:50:52 ERROR 404: Not Found.

=======> ERROR: Downloading 'http://rlog.googlecode.com/files/rlog-1.4.tar.gz' failed.
prt-get: error while install

-- Packages where install failed
rlog

Libcamberra

https://pastebin.com/cvQdnHxu

gtk-doc

https://pastebin.com/P4AQgLAS

**Comment by tsaop** [comment]
rlog and libcanberra are pulled from Romster's repo. Please contact him to fix the ports.
For rlog, pulling the source from github should suffice.
For encfs, you seem to have pasted the rlog output again.
For libcanberra please delete /usr/ports/work/libcanberra and try again
For gtk-doc, you need  to install the docbook-xml package (pay attention to its post-install script, that needs to be run to populate the catalog)

**Comment by ghost** [comment]
> For libcanberra please delete /usr/ports/work/libcanberra and try again

Packages are compiled on RAM. After compile, all tmp archives are deleted. So, deleting "/usr/ports/work/libcanberra" doesn't solve the problem because this folder doesn't exist after compile.

Docbook-xml already installed. About rlog and encfs, i'll contact him. 

Thanks for your help.

**Comment by ghost** [comment]
Ok. Now the only problem is with kfilemetadata, baloo and baloo-widgets:


kfilemetadata: https://pastebin.com/ip94uzi8

baloo: https://pastebin.com/ktiw8Z6k (Yeah, the shows kfilemetadata instead baloo.)

baloo-widgets: https://pastebin.com/2DxR2bdz (the same problem)

**Comment by ghost** [comment]
Baloo and baloo-widgets doesn't compile because they need kfilemetadata, but kfilemetadata doesn't compile successfully.

Please, try compile kfilemetadata and see what happens.

**Comment by tsaop** [comment]
I tried it right now and it compiles successfully.
I don't see an explicit error in your log: prt-get just seems to report the build as failed.

Can you try to build manually kfilemetadata?

**Comment by therealromster** [comment]
cd /usr/ports/kf5
prtverify -m missing-deps -c /usr/ports/opt -c /usr/ports/core -c /usr/ports/xorg/ -c /usr/ports/contrib/ -c /usr/ports/kf5 *
ERROR  kf5/graphviz ............. missing dependency: glut
ERROR  kf5/k3b .................. missing dependency: kjobwidgest
ERROR  kf5/kget ................. missing dependency: sqlite
ERROR  kf5/kmymoney ............. missing dependency: identitymanagement
ERROR  kf5/ktp-accounts-kcm ..... missing dependency: kconfigwigdets
ERROR  kf5/luajit ............... missing dependency: #
ERROR  kf5/luajit ............... missing dependency: Depends
ERROR  kf5/luajit ............... missing dependency: on
ERROR  kf5/opencolorio .......... missing dependency: yaml
ERROR  kf5/sparsehash ........... missing dependency: #
ERROR  kf5/sparsehash ........... missing dependency: Depends
ERROR  kf5/sparsehash ........... missing dependency: on

**Comment by tsaop** [comment]
Should be fixed now, thanks Romster.

**Comment by ghost** [comment]
Still not working: https://pastebin.com/RDXdHziW

Also, forget. Thanks for your help!

**Comment by tsaop** [comment]
Hello,

it seems you have a custom installed ffmpeg in /usr/local.
You need to remove it and install ffmpeg from contrib.
